stages:
- test
- build

tests:
  image: linkyard/docker-sbt
  stage: test
  cache:
    paths:
      - ~/.sbt/
      - ~/.ivy2/
  script:
    - sbt test

generate plugin:
  image: linkyard/docker-sbt
  stage: build
  cache:
    paths:
      - ~/.sbt/
      - ~/.ivy2/
  script:
    - sbt "esplugin 5.6.3" "esplugin 5.6.0" "esplugin 5.6.1" "esplugin 5.5.1"

  artifacts:
    paths:
      - target/escova*.zip
    expire_in: 1 week
