language: scala
sudo: false
jdk: oraclejdk8
env:
- ELASTIC_VERSION=5.6.3
- ELASTIC_VERSION=5.6.8
- ELASTIC_VERSION=5.6.9
- ELASTIC_VERSION=5.6.10
- ELASTIC_VERSION=5.6.13
scala:
- 2.12.4
sbt_args: "-mem 1500"
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}" test "project esplugin" "esplugin ${ELASTIC_VERSION}"
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
deploy:
  provider: releases
  file_glob: true
  file: modules/escova-esplugin/target/escova-*-for-es-*.zip
  skip_cleanup: true
  api_key:
    secure: bvlvYasrYzPhNib0dyil/UCcdA4YFsnnFHyLqHN780qJyZZ8aVTkL0Bv4DScTskeJP6VYbMCvjyfo5lRDG/pcbHtHTxARZ+bWqAIH7ChYabK1gbbpWntL+0kPmLcIFlgnq3LQr5A0omcuW0WMrgXm87/w+vkr5fAER2N1H4fLFP+PtKR6CnreONOZO0CPC82q5qHka2ufAGXo9gO0q0QIY6ubJ9immS6GxpLBuIc4L0Xz+/YZtvSIqe9TymoPr8x/b8E8rLoXEfnwSx7//Ks+352XrNIRC8VfSlkWzJ6bXsdXgayGhod4c1RkJ9zBzlSRwOO/5fPP78jwL5ao1irPI6oJJX8rNLxpT0LU1+TJf+RTKCngZrjMhSDVmvSql+wNvJk74SGzSUH+IIWkXU8bqMYt+KkYDndOPgDvOYHljO+nMsxmW7V13IKVuzO4nGgX2MPEKv+0f8dHtPxggLqOSLPEjmAVe/VyK8Sow8s+cCuFayyJSlQhUUzE4rxMqKUkK2729hWHlFdqqNhbA6+2/QZEfkX7h8pzcIy7PwE6DnNq4uka7xrb5yaK16OhTvD2y1P7WBR7r36LLaXxsWNmZtPejfsMaswNyCX7f/ul8KUqX5e9qmCgY3UjUmIMRs24LMkwmoXW6Cn/3NAhX/VgCeHUakcmA88Car2yYVOdwI=
  on:
    tags: true
    repo: openshine/escova
